### ISSUE TITLE
How can we handle different dimensions for different domains?

### ISSUE THREAD

**Issue by juhha1** [KrishnaswamyLab/scMMGAN#2]
Hi, thanks for your research and for sharing code.
I would like to test this method in some data, but I am having an issue.

From the example source code, x1 and x2 are set to have same same dimensionalities.
`x1 = np.random.normal(-5, 1, [10000, 100])
x2 = np.random.normal(5, 1, [10000, 100])`
I think in this scenario, it means there are same number of data instances (10,000) and same number of gene expressions (100) overlapped between both domains.
But when we want to try 2 domains with (1) different number of data instances and (2) different number of gene expressions, I think this will be a problem (for example: when we are given [123456, 100] and [54321, 900]).
In this case, how can we apply this method?

When I simply tested with 
`x1 = np.random.normal(-5, 1, [10000, 100])
x2 = np.random.normal(5, 1, [20000, 200])`
this gave me an error.

Thanks for reading my question!

**Comment by mattamodio** [comment]
I believe your error would have been caused by a missing import statement,
which I have now corrected, please see the newest commit. There is no
conceptual requirement of using datasets of the same dimensionality, as the
correspondence loss is calculated within each domain separately first and
then compared. Thanks for your question!

**Comment by juhha1** [comment]
I just checked why my error occurred and found that it happened when there were any all 0 vectors exists in any Eigenvectors. I don't exactly know why this happens, but the code works fine without bad examples where their Eigenvectors are all 0s.
Thanks for your assistance.
